// AUTO-GENERATED by scripts/import-linkedin-data.js — do not edit by hand.
// Add manual entries in src/data/timeline.ts instead.
import type { TimelineEntry } from "../types";

export const importedTimeline: TimelineEntry[] = [];
